### PR TITLE
manila: Allow using keystone v3 API

### PR DESCRIPTION
**Pull request by vuntz**
Backport of https://github.com/crowbar/crowbar-openstack/pull/59

### CODE REVIEW

**Comment by vuntz** [comment]
For the record, gating can't pass because there's a new directory in the package so the build of the package fails.

**Comment by toabctl** [comment]
+1

**Comment by vuntz** [comment]
@rhafer any +1/-1 on this? I'd like to merge (and gating can't pass due to the patch creating a new directory).

**Comment by rhafer** [comment]
+1

**Pull request merged**
